import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Polymorph / Next.js</title>
        <meta name="description" content="Generated by Polymorph" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://polymorph.so/">Polymorph</a> on <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Get started by editing{' '}
          <code>pages/index.js</code>
        </p>

        <div>
          <a href="https://docs.polymorph.so/">
            <h2>Polymorph &rarr;</h2>
            <p>Find usage and configuration options.</p>
          </a>

          <a href="https://nextjs.org/docs">
            <h2>Next.js &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      <style jsx>{`
        main{
          max-width: 690px;
          padding: 30px;
          margin: 30px auto;
        }
      `}</style>
    </div>
  )
}